### ISSUE TITLE
`method_missing` when calling faraday does not preserve `verify_ssl` settings

### ISSUE THREAD

**Issue by tunacado** [ansible/ansible_tower_client_ruby#121]
When using `faraday` for `get` calls, it falls to `method_missing` in order to get the instance to respond to `get`.  When this happens, if you have `verify_ssl` set to `false` it will not pass this on.

Example reproducer:
```
require 'ansible_tower_client'

ansible = AnsibleTowerClient::Connection.new(username: "admin",
                                             password: "tower-password",
                                             base_url: "https://tower-address.com",
                                             verify_ssl: false)

inventories = ansible.api.inventories
inventories.all.each { |inventory| puts inventory }
```

And the error:
```
Traceback (most recent call last):
	8: from ansible_reproducer.rb:9:in `<main>'
	7: from ansible_reproducer.rb:9:in `each'
	6: from ansible_reproducer.rb:9:in `each'
	5: from /var/lib/gems/2.5.0/gems/ansible_tower_client-0.18.0/lib/ansible_tower_client/collection.rb:21:in `block in find_all_by_url'
	4: from /var/lib/gems/2.5.0/gems/ansible_tower_client-0.18.0/lib/ansible_tower_client/collection.rb:21:in `loop'
	3: from /var/lib/gems/2.5.0/gems/ansible_tower_client-0.18.0/lib/ansible_tower_client/collection.rb:22:in `block (2 levels) in find_all_by_url'
	2: from /var/lib/gems/2.5.0/gems/ansible_tower_client-0.18.0/lib/ansible_tower_client/collection.rb:50:in `fetch_more_results'
	1: from /var/lib/gems/2.5.0/gems/ansible_tower_client-0.18.0/lib/ansible_tower_client/api.rb:114:in `method_missing'
/var/lib/gems/2.5.0/gems/ansible_tower_client-0.18.0/lib/ansible_tower_client/api.rb:129:in `rescue in method_missing': SSL_connect returned=1 errno=0 state=error: certificate verify failed (self signed certificate) (AnsibleTowerClient::SSLError)
```

Reproducing this is dependent on [this commit](https://github.com/ansible/ansible_tower_client_ruby/pull/120).

**Comment by robbmanes** [comment]
Dependent on PR #120
