### ISSUE TITLE
handle "end of file reached" somehow

### ISSUE THREAD

**Issue by Vitexus** [ansible/ansible_tower_client_ruby#148]
There is real life example from ManageIQ: ( @Fryguy can know anything about ?)

```
[----] E, [2023-01-10T13:58:28.144784 #564289:2af0cc228c28] ERROR -- : Q-task_id([r37587_service_template_provision_task_63191]) <AEMethod setup_sesu_for_tenant_user_group>  (run ansible job) - [end of file reached (MiqException::MiqOrchestrationProvisionError)]
(drbunix:///tmp/automation_engine20230110-564289-bpb4ob) /opt/manageiq/manageiq-gemset/gems/ansible_tower_client-0.21.3/lib/ansible_tower_client/api.rb:134:in `rescue in method_missing'
(drbunix:///tmp/automation_engine20230110-564289-bpb4ob) /opt/manageiq/manageiq-gemset/gems/ansible_tower_client-0.21.3/lib/ansible_tower_client/api.rb:121:in `method_missing'
(drbunix:///tmp/automation_engine20230110-564289-bpb4ob) /opt/manageiq/manageiq-gemset/gems/ansible_tower_client-0.21.3/lib/ansible_tower_client/collection.rb:31:in `find'
(drbunix:///tmp/automation_engine20230110-564289-bpb4ob) /opt/manageiq/manageiq-gemset/bundler/gems/manageiq-providers-ansible_tower-6e377778b290/app/models/manageiq/providers/ansible_tower/automation_manager/configuration_script.rb:50:in `provider_object'
(drbunix:///tmp/automation_engine20230110-564289-bpb4ob) /var/www/miq/vmdb/app/models/mixins/provider_object_mixin.rb:14:in `block in with_provider_object'
(drbunix:///tmp/automation_engine20230110-564289-bpb4ob) /var/www/miq/vmdb/app/models/provider.rb:58:in `with_provider_connection'
(drbunix:///tmp/automation_engine20230110-564289-bpb4ob) /opt/manageiq/manageiq-gemset/bundler/gems/manageiq-providers-ansible_tower-6e377778b290/app/models/manageiq/providers/ansible_tower/automation_manager.rb:10:in `with_provider_connection'
(drbunix:///tmp/automation_engine20230110-564289-bpb4ob) /var/www/miq/vmdb/app/models/mixins/provider_object_mixin.rb:12:in `with_provider_object'
(drbunix:///tmp/automation_engine20230110-564289-bpb4ob) /opt/manageiq/manageiq-gemset/bundler/gems/manageiq-providers-ansible_tower-6e377778b290/app/models/manageiq/providers/ansible_tower/automation_manager/configuration_script.rb:36:in `run'
(drbunix:///tmp/automation_engine20230110-564289-bpb4ob) /opt/manageiq/manageiq-gemset/bundler/gems/manageiq-providers-ansible_tower-6e377778b290/app/models/manageiq/providers/ansible_tower/automation_manager/job.rb:33:in `raw_create_stack'
(drbunix:///tmp/automation_engine20230110-564289-bpb4ob) /opt/manageiq/manageiq-gemset/bundler/gems/manageiq-providers-ansible_tower-6e377778b290/app/models/manageiq/providers/ansible_tower/automation_manager/job.rb:27:in `block in create_stack'
(drbunix:///tmp/automation_engine20230110-564289-bpb4ob) /opt/manageiq/manageiq-gemset/bundler/gems/manageiq-providers-ansible_tower-6e377778b290/app/models/manageiq/providers/ansible_tower/automation_manager/job.rb:26:in `tap'
(drbunix:///tmp/automation_engine20230110-564289-bpb4ob) /opt/manageiq/manageiq-gemset/bundler/gems/manageiq-providers-ansible_tower-6e377778b290/app/models/manageiq/providers/ansible_tower/automation_manager/job.rb:26:in `create_stack'
(drbunix:///tmp/automation_engine20230110-564289-bpb4ob) /opt/manageiq/manageiq-gemset/bundler/gems/manageiq-automation_engine-c798cda01ffc/lib/miq_automation_engine/service_models/miq_ae_service_manageiq-providers-ansible_tower-automation_manager-job.rb:9:in `create_job'
(drbunix:///tmp/automation_engine20230110-564289-bpb4ob) /usr/share/ruby/drb/drb.rb:1635:in `perform_without_block'
(drbunix:///tmp/automation_engine20230110-564289-bpb4ob) /usr/share/ruby/drb/drb.rb:1595:in `perform'
(drbunix:///tmp/automation_engine20230110-564289-bpb4ob) /usr/share/ruby/drb/drb.rb:1679:in `block (2 levels) in main_loop'
(drbunix:///tmp/automation_engine20230110-564289-bpb4ob) /usr/share/ruby/drb/drb.rb:1675:in `loop'
(drbunix:///tmp/automation_engine20230110-564289-bpb4ob) /usr/share/ruby/drb/drb.rb:1675:in `block in main_loop'
``` 
The main missing piece is here in api.rb:

/gems/ansible_tower_client-0.21.3/lib/ansible_tower_client/api.rb:134:in `**rescue in method_missing**'

So please add rescue method for this problem.

The best solution for me is add the broken respone fragment recieved from AWX to log. 
This can help figure out what is wrong with AWX.

**Comment by Fryguy** [comment]
cc @nasark @agrare - This is for AWX provider

(Aside, I seem to have had my permissions removed here - maybe we should ask Ansible team to transfer this repo to our org)

**Comment by agrare** [comment]
> (Aside, I seem to have had my permissions removed here - maybe we should ask Ansible team to transfer this repo to our org)

Same here

**Comment by agrare** [comment]
@Vitexus is this something that you hit occasionally or every single API request?

**Comment by Vitexus** [comment]
@agrare every few days. This issue is not critical for other people i think...
The priority is "nice to have"

Maybe is my problem somewhere inside of k8s, but current "nonsolution" with no rescue method won't help me the source of problem.

**Comment by agrare** [comment]
Finally found the other issue I was trying to recall, https://github.com/ManageIQ/manageiq/discussions/21939#discussioncomment-3148867

I'm wondering if this EOF reached might be the cause of that as well.
